"""Type stubs for pyopath - a pathlib clone implemented in Rust."""

from collections.abc import Sequence
from typing import IO, Self

__version__: str
__all__: list[str] = [
    "Path",
    "PosixPath",
    "PurePath",
    "PurePosixPath",
    "PureWindowsPath",
    "WindowsPath",
]

class PurePath:
    """A path object that provides lexical operations only (no filesystem access)."""

    def __new__(cls, *args: str | PurePath) -> Self: ...

    # Properties
    @property
    def drive(self) -> str: ...
    @property
    def root(self) -> str: ...
    @property
    def anchor(self) -> str: ...
    @property
    def parts(self) -> Sequence[str]: ...
    @property
    def name(self) -> str: ...
    @property
    def suffix(self) -> str: ...
    @property
    def suffixes(self) -> Sequence[str]: ...
    @property
    def stem(self) -> str: ...
    @property
    def parent(self) -> Self: ...
    @property
    def parents(self) -> Sequence[Self]: ...

    # Methods
    def is_absolute(self) -> bool: ...
    def is_relative_to(self, other: Self | str) -> bool: ...
    def relative_to(self, other: Self | str, *, walk_up: bool = False) -> Self: ...
    def joinpath(self, *args: str | Self) -> Self: ...
    def with_name(self, name: str) -> Self: ...
    def with_stem(self, stem: str) -> Self: ...
    def with_suffix(self, suffix: str) -> Self: ...
    def as_posix(self) -> str: ...

    # Dunder methods
    def __fspath__(self) -> str: ...
    def __truediv__(self, other: str | Self) -> Self: ...
    def __rtruediv__(self, other: str) -> Self: ...
    def __hash__(self) -> int: ...
    def __eq__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...
    def __lt__(self, other: Self) -> bool: ...
    def __le__(self, other: Self) -> bool: ...
    def __gt__(self, other: Self) -> bool: ...
    def __ge__(self, other: Self) -> bool: ...

class PurePosixPath(PurePath):
    """A POSIX path object (uses forward slashes, no drive letters)."""

    def __new__(cls, *args: str | PurePath) -> Self: ...

class PureWindowsPath(PurePath):
    """A Windows path object (uses backslashes, has drive letters)."""

    def __new__(cls, *args: str | PurePath) -> Self: ...

class StatResult:
    """Result of a stat() call."""

    @property
    def st_mode(self) -> int: ...
    @property
    def st_size(self) -> int: ...
    @property
    def st_mtime(self) -> float: ...
    @property
    def st_atime(self) -> float: ...
    @property
    def st_ctime(self) -> float: ...

class Path(PurePath):
    """A concrete path that provides filesystem operations."""

    def __new__(cls, *args: str | PurePath) -> Self: ...

    # Filesystem query methods
    def exists(self) -> bool: ...
    def is_file(self) -> bool: ...
    def is_dir(self) -> bool: ...
    def is_symlink(self) -> bool: ...
    def stat(self) -> StatResult: ...
    def lstat(self) -> StatResult: ...

    # Path resolution
    def absolute(self) -> Self: ...
    def resolve(self, strict: bool = False) -> Self: ...
    def readlink(self) -> Self: ...

    # Directory operations
    def mkdir(
        self, mode: int = 0o777, parents: bool = False, exist_ok: bool = False
    ) -> None: ...
    def rmdir(self) -> None: ...
    def iterdir(self) -> Sequence[Self]: ...
    def glob(self, pattern: str) -> Sequence[Self]: ...
    def rglob(self, pattern: str) -> Sequence[Self]: ...

    # File operations
    def touch(self, exist_ok: bool = True) -> None: ...
    def unlink(self, missing_ok: bool = False) -> None: ...
    def rename(self, target: Self | str) -> Self: ...
    def replace(self, target: Self | str) -> Self: ...

    # Read/write operations
    def read_text(self, encoding: str | None = None) -> str: ...
    def write_text(self, data: str, encoding: str | None = None) -> int: ...
    def read_bytes(self) -> bytes: ...
    def write_bytes(self, data: bytes) -> int: ...

    # File opening
    def open(
        self,
        mode: str = "r",
        buffering: int = -1,
        encoding: str | None = None,
        errors: str | None = None,
        newline: str | None = None,
    ) -> IO[str]: ...

    # Static methods
    @staticmethod
    def cwd() -> Path: ...
    @staticmethod
    def home() -> Path: ...

class PosixPath(Path, PurePosixPath):
    """A POSIX concrete path with filesystem operations."""

    def __new__(cls, *args: str | PurePath) -> Self: ...
    @staticmethod
    def cwd() -> PosixPath: ...
    @staticmethod
    def home() -> PosixPath: ...

class WindowsPath(Path, PureWindowsPath):
    """A Windows concrete path with filesystem operations."""

    def __new__(cls, *args: str | PurePath) -> Self: ...
    @staticmethod
    def cwd() -> WindowsPath: ...
    @staticmethod
    def home() -> WindowsPath: ...
